baseURL = "https://sboots.ca/"
languageCode = "en-us"
title = "Sean Boots"

theme = "hugo-theme-bootstrap4-blog"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 20
# optionally override the site's footer with custom copyright text
copyright = "© Sean Boots. Licensed under a Creative Commons Attribution license (CC BY 4.0)."
googleAnalytics = "UA-154962815-1"
#disqusShortname = "XYW"


# ignoreLogs = ['shortcode-twitter-getremote']

[privacy]
  [privacy.x]
    simple = true


enableRobotsTXT = true

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Link 1"
  url = "https://example.com"

[[menu.sidebar]]
  name = "Link 2"
  url = "https://example.org"

#[[menu.navbar]]
#  name = "Link 1"
#  url = "https://example.org"


# Theme variables
#
[params]
  # Site author
  author = "Sean Boots"
  rssDescription = "Recent content on Sean Boots’ blog"

  # Description/subtitle for homepage (can be Markdown)
  description = "Technology, public services, and people. But mostly people."

  # Show header (default: true)
  header_visible = true

  # Format dates with Go's time formatting
  date_format = "January 2, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # show sharing icons on pages/posts (default: true)
  sharingicons = false

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  disable_sri = true

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/)."

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "sboots"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark.parser]
  autoHeadingIDType = "blackfriday"

[markup.goldmark.renderer]
    unsafe = true
